name: mStudios
favicon: null
layout_spectrum: 0.1660233938600868
typography_spectrum: 0.47736678598448634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#5d828b'
    - '#6a638c'
    - '#878656'
    - '#476766'
  brandStrength: 0.75
  lightness: 0.6855006814002991
  saturation: 0.25
  rhythmicContrast: 0.9846382674295455
purpose: []
